#!/usr/bin/env python3
"""mb — Metabase API wrapper.

Reads run freely. Ad-hoc SQL is checked read-only. Every mutation captures a
restore point first.

Resolution:
  METABASE_URL  process env -> .metabase/context.md frontmatter -> .env files
  METABASE_API_KEY  process env -> .env files   (context.md never holds the key)

Both the context file and .env discovery are anchored at the project root (the
nearest ancestor containing .git), so the tool behaves identically from any
subdirectory.

The read-only check is a speed bump, not a sandbox. A determined writer can get
past any string-level check (see FUNC_DENY). The durable control is a read-only
database role on the Metabase connection.
"""

import argparse
import difflib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ENV_CANDIDATES = [".env", "dataops/modelling/.env", ".metabase/.env"]
GEN_MARKER = "<!-- generated by `mb bootstrap`; edits below this line are kept -->"

DISPLAYS = {
    "table", "scalar", "bar", "line", "pie", "row", "area", "combo", "pivot",
    "funnel", "map", "gauge", "progress", "number", "smartscalar", "waterfall",
    "sankey", "object", "trend", "detail", "list",
}

# Fields cmd_update may PUT. cmd_restore restores this same set from a
# snapshot — the two MUST stay in sync, or the tool can inflict damage it
# cannot undo.
MUTABLE = {
    "dataset_query", "name", "description", "display", "visualization_settings",
    "collection_id", "collection_position", "archived", "result_metadata",
    "type", "parameters", "cache_ttl",
}

# Same contract for dashboards. `dashcards` carries the layout AND the filter
# wiring, so a PUT that omits a dashcard REMOVES it from the dashboard — always
# send the full list you want to end up with.
DASH_MUTABLE = {
    "name", "description", "parameters", "dashcards", "tabs", "collection_id",
    "collection_position", "archived", "cache_ttl", "auto_apply_filters",
    "width",
}

# ---------------------------------------------------------------- read-only

LEADING_OK = {"SELECT", "WITH", "SHOW", "EXPLAIN", "TABLE", "VALUES",
              "DESCRIBE", "DESC"}

# Dangerous *inside* an otherwise read-only statement — chiefly via
# data-modifying CTEs (WITH x AS (DELETE ...)) and FOR UPDATE row locks.
# Keywords that are only dangerous as a statement's first token (SET, COPY,
# CALL, COMMENT, CLUSTER, LOCK, EXECUTE, IMPORT, RESET, SECURITY, VACUUM,
# REINDEX, REFRESH, PREPARE, DISCARD) are deliberately absent: LEADING_OK plus
# the single-statement rule already make them unreachable, and blocking them
# anywhere false-positives on ordinary column names like `comment` or `set`.
ALWAYS_BLOCKED = {
    "INSERT", "UPDATE", "DELETE", "MERGE", "TRUNCATE", "DROP", "CREATE",
    "ALTER", "GRANT", "REVOKE",
}

# Read-only-looking functions that write, kill sessions, or read the filesystem.
# The keyword scan cannot see these: their payload lives in a string literal,
# which strip_sql (correctly) blanks.
FUNC_DENY = {
    "dblink", "dblink_exec", "dblink_send_query",
    "nextval", "setval",
    "lo_import", "lo_export", "lo_unlink",
    "pg_read_file", "pg_read_binary_file", "pg_ls_dir", "pg_stat_file",
    "pg_terminate_backend", "pg_cancel_backend",
    "pg_reload_conf", "pg_rotate_logfile", "pg_switch_wal",
    "pg_create_restore_point", "pg_drop_replication_slot",
    "pg_logical_slot_get_changes", "query_to_xml", "pg_sleep",
}


class Unterminated(Exception):
    pass


def strip_sql(sql: str) -> str:
    """Blank comments and string literals so nothing hides inside them.

    Handles dollar-quoting ($$..$$, $tag$..$tag$) and E'' backslash escapes.
    Raises Unterminated if a literal or block comment never closes — failing
    loudly beats silently swallowing the rest of the statement, which is how a
    hidden second statement slips through.
    """
    out = []
    i, n = 0, len(sql)
    while i < n:
        # dollar-quoted string: $$...$$ or $tag$...$tag$
        m = re.match(r"\$([A-Za-z_][A-Za-z_0-9]*)?\$", sql[i:])
        if m:
            tag = m.group(0)
            end = sql.find(tag, i + len(tag))
            if end == -1:
                raise Unterminated(f"unterminated dollar-quoted string {tag}")
            out.append(" ")
            i = end + len(tag)
            continue
        two = sql[i:i + 2]
        if two == "/*":
            depth, i = 1, i + 2
            while i < n and depth:
                if sql[i:i + 2] == "/*":
                    depth += 1
                    i += 2
                elif sql[i:i + 2] == "*/":
                    depth -= 1
                    i += 2
                else:
                    i += 1
            if depth:
                raise Unterminated("unterminated block comment")
            out.append(" ")
        elif two == "--":
            while i < n and sql[i] != "\n":
                i += 1
            out.append(" ")
        elif sql[i] in "'\"":
            q = sql[i]
            # E'...' / e'...' honours backslash escapes
            esc = q == "'" and i > 0 and sql[i - 1] in "Ee" and (
                i < 2 or not (sql[i - 2].isalnum() or sql[i - 2] == "_"))
            i += 1
            closed = False
            while i < n:
                c = sql[i]
                if esc and c == "\\" and i + 1 < n:
                    i += 2
                    continue
                if c == q:
                    if i + 1 < n and sql[i + 1] == q:  # '' escape
                        i += 2
                        continue
                    i += 1
                    closed = True
                    break
                i += 1
            if not closed:
                raise Unterminated("unterminated string literal")
            out.append(" ")
        else:
            out.append(sql[i])
            i += 1
    return "".join(out)


def assert_readonly(sql: str) -> None:
    try:
        clean = strip_sql(sql).strip()
    except Unterminated as e:
        die(str(e))
    if not clean:
        die("empty query")

    body = clean.rstrip()
    if body.endswith(";"):
        body = body[:-1]
    if ";" in body:
        die("multiple statements — submit one statement at a time")

    lead = body.lstrip("﻿ \t\r\n(")
    first = re.match(r"[A-Za-z]+", lead)
    if not first or first.group(0).upper() not in LEADING_OK:
        got = first.group(0).upper() if first else "?"
        die(f"leading keyword {got!r} is not read-only "
            f"(allowed: {', '.join(sorted(LEADING_OK))})")

    words = [w.upper() for w in re.findall(r"[A-Za-z_][A-Za-z_0-9]*", body)]
    hits = sorted(set(words) & ALWAYS_BLOCKED)
    if hits:
        die(f"write/DDL keyword(s) present: {', '.join(hits)}")

    # SELECT ... INTO newtable is DDL wearing a SELECT hat.
    for idx, w in enumerate(words):
        if w == "INTO" and (idx == 0 or words[idx - 1] != "INSERT"):
            die("SELECT … INTO creates a table — use a plain SELECT")

    fns = sorted({w.lower() for w in words} & FUNC_DENY)
    if fns:
        die(f"function(s) with side effects: {', '.join(fns)}")


def die(reason: str) -> None:
    print(f"BLOCKED: {reason}", file=sys.stderr)
    sys.exit(2)


# ------------------------------------------------------------------- config

def project_root() -> Path:
    here = Path.cwd().resolve()
    home = Path.home().resolve()
    for base in [here, *here.parents]:
        if (base / ".git").exists():
            return base
        if base == home:
            break
    return here


ROOT = project_root()
CTX_DIR = ROOT / ".metabase"
CTX_FILE = CTX_DIR / "context.md"
BACKUP_DIR = CTX_DIR / "restore-points"


def parse_env_line(line: str):
    line = line.strip()
    if line.startswith("export "):
        line = line[7:].lstrip()
    if not line or line.startswith("#") or "=" not in line:
        return None
    k, v = line.split("=", 1)
    k, v = k.strip(), v.strip()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", k):
        return None
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
        v = v[1:-1]                       # matched quote pair only
    else:
        v = re.sub(r"\s+#.*$", "", v).strip()   # unquoted trailing comment
    return k, v


def load_env_files() -> dict:
    found, seen = {}, set()
    here = Path.cwd().resolve()
    bases = [here, *here.parents]
    if ROOT not in bases:
        bases.append(ROOT)
    for base in bases:
        for rel in ENV_CANDIDATES:
            p = (base / rel).resolve()
            if p in seen or not p.is_file():
                continue
            seen.add(p)
            for line in p.read_text(errors="ignore").splitlines():
                kv = parse_env_line(line)
                if kv:
                    found.setdefault(kv[0], (kv[1], str(p)))
        if (base / ".git").exists():
            break
    return found


def context_url():
    if not CTX_FILE.is_file():
        return None
    m = re.search(r"^url:\s*(\S+)", CTX_FILE.read_text(), re.M)
    return m.group(1).strip("'\"") if m else None


_CFG = {}


def config() -> tuple[str, str]:
    if _CFG:
        return _CFG["url"], _CFG["key"]
    env = load_env_files()
    key = os.environ.get("METABASE_API_KEY")
    key_src = "process environment"
    if not key and "METABASE_API_KEY" in env:
        key, key_src = env["METABASE_API_KEY"]
        key_src = f"{key_src}"
    url = os.environ.get("METABASE_URL")
    url_src = "process environment"
    if not url:
        url = context_url()
        url_src = str(CTX_FILE)
    if not url and "METABASE_URL" in env:
        url, url_src = env["METABASE_URL"]

    missing = []
    if not key:
        missing.append("METABASE_API_KEY (process env or a .env file)")
    if not url:
        missing.append(f"METABASE_URL (process env, {CTX_FILE} frontmatter, "
                       f"or a .env file)")
    if missing:
        die("missing config: " + "; ".join(missing) +
            f"\n  project root: {ROOT}"
            f"\n  run `mb bootstrap` once METABASE_URL is set")
    if not url.startswith(("http://", "https://")):
        die(f"METABASE_URL must start with http:// or https:// (got {url!r} "
            f"from {url_src})")
    _CFG.update(url=url.rstrip("/"), key=key,
                url_src=url_src, key_src=key_src)
    return _CFG["url"], _CFG["key"]


# ---------------------------------------------------------------- transport

def api(method: str, path: str, body=None, form=None, raw=False, timeout=120,
        allow_fail=False):
    """Call the Metabase API.

    `path` is relative to /api — pass "/card/5", NOT "/api/card/5" (that
    yields /api/api/card/5 and a 404 that reads like a missing endpoint).
    allow_fail=True returns None on an HTTP error instead of exiting, for
    probes where "not found" is a legitimate answer.
    """
    url, key = config()
    headers = {"x-api-key": key}
    data = None
    if form is not None:
        data = urllib.parse.urlencode(form).encode()
        headers["Content-Type"] = "application/x-www-form-urlencoded"
    elif body is not None:
        data = json.dumps(body).encode()
        headers["Content-Type"] = "application/json"
    try:
        req = urllib.request.Request(f"{url}/api{path}", data=data,
                                     method=method, headers=headers)
        with urllib.request.urlopen(req, timeout=timeout) as r:
            payload = r.read()
    except urllib.error.HTTPError as e:
        if allow_fail:
            return None
        detail = e.read().decode(errors="replace")[:800]
        extra = ""
        if e.code in (401, 403):
            extra = f"\n  key from: {_CFG.get('key_src', '?')}"
        print(f"HTTP {e.code} on {method} {url}/api{path}{extra}\n{detail}",
              file=sys.stderr)
        sys.exit(1)
    except urllib.error.URLError as e:
        print(f"connection failed to {url} (from {_CFG.get('url_src','?')}): "
              f"{e.reason}\n"
              f"  If the host resolved but timed out: check the VPN, and that "
              f"the shell is unsandboxed.\n"
              f"  If the host did not resolve: check METABASE_URL for a typo.",
              file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"bad URL {url!r} (from {_CFG.get('url_src','?')}): {e}",
              file=sys.stderr)
        sys.exit(1)
    if raw:
        return payload.decode(errors="replace")
    return json.loads(payload) if payload else None


def out(obj):
    print(json.dumps(obj, indent=2, default=str))


# ----------------------------------------------------------------- commands

def rows_from_dataset(res):
    """Normalise a /api/dataset response to list-of-dicts.

    Keys off cols[].name — Metabase already de-duplicates it (id, id_2) —
    because display_name is NOT unique and collapsing on it silently drops
    columns and returns the wrong values.
    """
    status = res.get("status") if isinstance(res, dict) else None
    if status == "failed":
        print(f"query failed: {res.get('error')}", file=sys.stderr)
        sys.exit(1)
    data = res["data"]
    cols = [c["name"] for c in data["cols"]]
    return [dict(zip(cols, r)) for r in data["rows"]]


def cmd_sql(a):
    assert_readonly(a.sql)
    res = api("POST", "/dataset", body={
        "database": a.db, "type": "native", "native": {"query": a.sql},
    })
    rows = rows_from_dataset(res)
    if a.limit and len(rows) > a.limit:
        print(f"note: {len(rows)} rows, showing first {a.limit} "
              f"(--limit 0 for all)", file=sys.stderr)
        rows = rows[:a.limit]
    out(rows)


def cmd_card(a):
    out(api("GET", f"/card/{a.id}"))


def _native_of(card):
    dq = card.get("dataset_query", {})
    stages = dq.get("stages") or []
    if len(stages) == 1 and isinstance(stages[0].get("native"), str):
        return stages[0]["native"], stages[0].get("template-tags") or {}
    nat = dq.get("native")
    if isinstance(nat, dict) and isinstance(nat.get("query"), str) and not stages:
        return nat["query"], nat.get("template-tags") or {}
    return None, {}


def cmd_sql_of(a):
    card = api("GET", f"/card/{a.id}")
    sql, tags = _native_of(card)
    if sql is not None and not a.compiled:
        if tags:
            print(f"-- note: {len(tags)} template tag(s); [[...]] blocks and "
                  f"{{{{tags}}}} are Metabase syntax, not runnable SQL",
                  file=sys.stderr)
        print(sql)
        return
    compiled = api("POST", "/dataset/native", body=card["dataset_query"])
    print(compiled["query"])


def _card_db(card):
    dq = card.get("dataset_query", {})
    return dq.get("database")


def cmd_run(a):
    if a.count:
        card = api("GET", f"/card/{a.id}")
        db = _card_db(card)
        if db:
            res = api("POST", "/dataset", body={
                "database": db, "type": "query",
                "query": {"source-table": f"card__{a.id}",
                          "aggregation": [["count"]]},
            }, timeout=300)
            if isinstance(res, dict) and res.get("status") != "failed":
                out({"card": a.id, "rows": res["data"]["rows"][0][0],
                     "counted": "server-side"})
                return
        # fall through to client-side count
    res = api("POST", f"/card/{a.id}/query/json", body={}, timeout=300)
    if isinstance(res, dict) and (res.get("error") or res.get("status") == "failed"):
        print(f"card {a.id} failed: {json.dumps(res)[:400]}", file=sys.stderr)
        sys.exit(1)
    if a.count:
        out({"card": a.id, "rows": len(res), "counted": "client-side"})
        return
    if a.limit and len(res) > a.limit:
        print(f"note: {len(res)} rows, showing first {a.limit} "
              f"(--limit 0 for all)", file=sys.stderr)
        res = res[:a.limit]
    out(res)


def _find_source_cards(node, acc):
    """Recursively collect every card id referenced anywhere in a query."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k in ("source-card", "source_card_id") and isinstance(v, int):
                acc.add(v)
            elif k == "source-table" and isinstance(v, str) and v.startswith("card__"):
                acc.add(int(v[6:]))
            else:
                _find_source_cards(v, acc)
    elif isinstance(node, list):
        for v in node:
            _find_source_cards(v, acc)
    return acc


def _norm_sql(s):
    return re.sub(r"\s+", " ", re.sub(r"--[^\n]*", "", s or "")).strip().lower()


def cmd_deps(a):
    dashes = api("GET", f"/card/{a.id}/dashboards") or []
    cards = api("GET", "/card") or []

    direct = []
    for c in cards:
        if c["id"] == a.id:
            continue
        refs = _find_source_cards(c.get("dataset_query", {}), set())
        if c.get("source_card_id"):
            refs.add(c["source_card_id"])
        if a.id in refs:
            direct.append({"id": c["id"], "name": c["name"]})

    result = {
        "card": a.id,
        "dashboards": [{"id": d["id"], "name": d.get("name")} for d in dashes],
        "sourced_by_cards": direct,
    }

    if a.deep:
        # transitive closure downward
        by_id = {c["id"]: c for c in cards}
        edges = {}
        for c in cards:
            refs = _find_source_cards(c.get("dataset_query", {}), set())
            if c.get("source_card_id"):
                refs.add(c["source_card_id"])
            for r in refs:
                edges.setdefault(r, set()).add(c["id"])
        seen, stack = set(), [a.id]
        while stack:
            cur = stack.pop()
            for child in edges.get(cur, ()):
                if child not in seen:
                    seen.add(child)
                    stack.append(child)
        seen.discard(a.id)
        result["transitive_dependents"] = [
            {"id": i, "name": by_id[i]["name"]} for i in sorted(seen)
            if i in by_id
        ]
        # frozen copies: native cards whose SQL closely matches this one's
        me = _norm_sql(_native_of(api("GET", f"/card/{a.id}"))[0])
        frozen = []
        if me and len(me) > 200:
            for c in cards:
                if c["id"] == a.id or c.get("source_card_id") == a.id:
                    continue
                other = _norm_sql(_native_of(c)[0])
                if not other or len(other) < 200:
                    continue
                ratio = difflib.SequenceMatcher(None, me, other).ratio()
                if ratio >= a.similarity:
                    frozen.append({"id": c["id"], "name": c["name"],
                                   "similarity": round(ratio, 3)})
        result["possible_frozen_copies"] = sorted(
            frozen, key=lambda x: -x["similarity"])
    out(result)


def cmd_search(a):
    params = {"q": a.q, "models": a.model}
    res = api("GET", "/search?" + urllib.parse.urlencode(params))
    items = res.get("data", res) if isinstance(res, dict) else res
    total = res.get("total") if isinstance(res, dict) else None
    rows = []
    for x in items[:a.limit] if a.limit else items:
        row = {"id": x["id"], "name": x["name"], "model": x.get("model")}
        coll = (x.get("collection") or {}).get("name")
        if coll:
            row["collection"] = coll
        for k in ("database_name", "table_name", "table_schema"):
            if x.get(k):
                row[k] = x[k]
        rows.append(row)
    payload = {"results": rows}
    if total is not None and total > len(rows):
        payload["total_matching"] = total
        payload["note"] = ("more matches than shown; search is best-effort — "
                           "the appdb index can lag, so GET /api/card is "
                           "authoritative")
    out(payload)


def cmd_dashboard(a):
    d = api("GET", f"/dashboard/{a.id}")
    if a.full:
        out(d)
        return
    params = {p["id"]: p for p in d.get("parameters", [])}
    cards = []
    for dc in d.get("dashcards", []):
        c = dc.get("card") or {}
        if not c.get("id"):
            continue
        entry = {
            "card_id": c["id"], "name": c.get("name"),
            "display": c.get("display"),
            "filters": {params.get(m["parameter_id"], {}).get("name", "?"):
                        m.get("target")
                        for m in dc.get("parameter_mappings", [])},
        }
        extra = [s.get("id") for s in dc.get("series", []) if s.get("id")]
        if extra:
            entry["series_cards"] = extra
        cards.append(entry)
    summary = {
        "id": d["id"], "name": d.get("name"),
        "parameters": [
            {"name": p.get("name"), "type": p.get("type"),
             "default": p.get("default")}
            for p in params.values()
        ],
        "cards": cards,
    }
    tabs = d.get("tabs") or []
    if tabs:
        summary["tabs"] = [{"id": t.get("id"), "name": t.get("name")}
                           for t in tabs]
        summary["note"] = "dashboard has tabs; cards above are flattened"
    out(summary)


def _ensure_gitignore():
    CTX_DIR.mkdir(parents=True, exist_ok=True)
    gi = CTX_DIR / ".gitignore"
    lines = gi.read_text().splitlines() if gi.exists() else []
    if "restore-points/" not in [ln.strip() for ln in lines]:
        lines.append("restore-points/")
        gi.write_text("\n".join(lines) + "\n")


def restore_point(obj_id: int, kind: str = "card") -> Path:
    """Snapshot a card or dashboard to .metabase/restore-points/.

    kind is part of the filename so `restore` can refuse to PUT a dashboard
    snapshot over a card (and vice versa) — the two shapes are not
    interchangeable and the mistake is silent if it lands.
    """
    obj = api("GET", f"/{kind}/{obj_id}")
    _ensure_gitignore()
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%dT%H%M%S")
    for n in range(1, 1000):
        suffix = "" if n == 1 else f"-{n}"
        p = BACKUP_DIR / f"{stamp}{suffix}__{kind}{obj_id}.json"
        try:
            with open(p, "x") as fh:
                json.dump(obj, fh, indent=2)
            return p
        except FileExistsError:
            continue
    die("could not allocate a unique restore-point filename")


def cmd_backup(a):
    kind = "dashboard" if a.dashboard else "card"
    results = []
    try:
        for i in a.ids:
            results.append({kind: i,
                            "restore_point": str(restore_point(i, kind))})
    finally:
        if results:
            out(results)


def _load_body(path):
    body = json.loads(Path(path).read_text())
    if not isinstance(body, dict):
        die(f"card JSON must be an object, got {type(body).__name__}")
    if not body:
        die("card JSON is empty — nothing to change")
    return body


def cmd_update(a):
    body = _load_body(a.file)
    unknown = set(body) - MUTABLE
    if unknown:
        die(f"refusing to PUT unexpected field(s): {', '.join(sorted(unknown))}. "
            f"Allowed: {', '.join(sorted(MUTABLE))}")
    rp = restore_point(a.id)
    res = api("PUT", f"/card/{a.id}", body=body)
    out({"updated": res["id"], "name": res["name"], "restore_point": str(rp)})


def cmd_create(a):
    body = _load_body(a.file)
    for req in ("name", "dataset_query", "display"):
        if req not in body:
            die(f"card JSON missing required field {req!r}")
    if body["display"] not in DISPLAYS:
        die(f"display {body['display']!r} is not a known Metabase display "
            f"({', '.join(sorted(DISPLAYS))})")
    if "collection_id" not in body and not a.allow_root:
        die("no collection_id — the card would land in the ROOT collection, "
            "which is the instance front page. Set collection_id, or pass "
            "--allow-root deliberately.")
    body.setdefault("visualization_settings", {})
    res = api("POST", "/card", body=body)
    out({"created": res["id"], "name": res["name"],
         "collection_id": res.get("collection_id")})


def cmd_create_dashboard(a):
    body = _load_body(a.file)
    if "name" not in body:
        die("dashboard JSON missing required field 'name'")
    if "collection_id" not in body and not a.allow_root:
        die("no collection_id — the dashboard would land in the ROOT "
            "collection, which is the instance front page. Set collection_id, "
            "or pass --allow-root deliberately.")
    unknown = set(body) - DASH_MUTABLE
    if unknown:
        die(f"refusing to POST unexpected field(s): {', '.join(sorted(unknown))}. "
            f"Allowed: {', '.join(sorted(DASH_MUTABLE))}")
    # Metabase creates a dashboard bare; parameters/dashcards land via PUT.
    create = {k: body[k] for k in ("name", "description", "collection_id",
                                   "collection_position") if k in body}
    res = api("POST", "/dashboard", body=create)
    did = res["id"]
    rest = {k: v for k, v in body.items() if k not in create}
    if rest:
        res = api("PUT", f"/dashboard/{did}", body=rest)
    out({"created": did, "name": res["name"],
         "collection_id": res.get("collection_id"),
         "dashcards": len(res.get("dashcards") or []),
         "parameters": len(res.get("parameters") or [])})


def cmd_update_dashboard(a):
    body = _load_body(a.file)
    unknown = set(body) - DASH_MUTABLE
    if unknown:
        die(f"refusing to PUT unexpected field(s): {', '.join(sorted(unknown))}. "
            f"Allowed: {', '.join(sorted(DASH_MUTABLE))}")
    if "dashcards" in body:
        cur = api("GET", f"/dashboard/{a.id}")
        have, send = len(cur.get("dashcards") or []), len(body["dashcards"])
        if send < have and not a.allow_removal:
            die(f"dashcards: sending {send} but the dashboard has {have}. "
                f"A PUT replaces the whole list, so this REMOVES "
                f"{have - send} card(s). Pass --allow-removal if that is "
                f"the intent.")
    rp = restore_point(a.id, "dashboard")
    res = api("PUT", f"/dashboard/{a.id}", body=body)
    out({"updated": res["id"], "name": res["name"],
         "dashcards": len(res.get("dashcards") or []),
         "restore_point": str(rp)})


# Metabase writes field references in TWO argument orders, and code that walks
# the JSON must handle both or it silently rewrites only half of them:
#   pMBQL  (inside card dataset_query):     ["field", {opts}, <id|name>]
#   legacy (inside parameter_mappings):     ["field", <id|name>, {opts}]
# See references/api-reference.md ("Field references come in two orders").
def walk_field_ids(node):
    """Yield every integer field id in a card query or dashcard mapping."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k in ("source-field", "source-table") and isinstance(v, int):
                yield v
            else:
                yield from walk_field_ids(v)
    elif isinstance(node, list):
        if len(node) >= 3 and node[0] == "field":
            if isinstance(node[2], int):
                yield node[2]
            elif isinstance(node[1], int):
                yield node[1]
        for x in node:
            yield from walk_field_ids(x)


def cmd_wiring(a):
    """Audit a dashboard's filter wiring for ids that belong to another DB.

    A mapping can reference a field from a DIFFERENT database than the card it
    is attached to — the dashboard still renders and the card still runs, only
    the filter is dead. Nothing in the UI shows this.
    """
    d = api("GET", f"/dashboard/{a.id}")
    # Resolve ids one at a time and cache. Pulling /database/<id>/metadata for
    # every database is minutes on a warehouse-sized instance; a dashboard
    # references a handful of fields.
    tbl_cache, fld_cache = {}, {}

    def table_of(tid):
        if tid not in tbl_cache:
            t = api("GET", f"/table/{tid}", allow_fail=True)
            tbl_cache[tid] = (t["db_id"], t["name"]) if t else None
        return tbl_cache[tid]

    def owner_of(fid):
        """-> (db_id, description) for a field id, else a table id, else None."""
        if fid in fld_cache:
            return fld_cache[fid]
        res = None
        f = api("GET", f"/field/{fid}", allow_fail=True)
        if f:
            t = table_of(f["table_id"])
            if t:
                res = (t[0], f"{t[1]}.{f['name']}")
        else:
            t = table_of(fid)          # might be a source-table id, not a field
            if t:
                res = (t[0], f"table {t[1]}")
        fld_cache[fid] = res
        return res

    pname = {p["id"]: p["name"] for p in d.get("parameters") or []}
    report, bad = [], 0
    for dc in d.get("dashcards") or []:
        cid = dc.get("card_id")
        if cid is None:
            continue
        cdb = (dc.get("card") or {}).get("database_id") \
            or api("GET", f"/card/{cid}")["dataset_query"]["database"]
        for m in dc.get("parameter_mappings") or []:
            for fid in sorted(set(walk_field_ids(m["target"]))):
                o = owner_of(fid)
                ok = bool(o) and o[0] == cdb
                bad += not ok
                report.append({
                    "card_id": cid, "card_db": cdb,
                    "parameter": pname.get(m["parameter_id"], m["parameter_id"]),
                    "id": fid,
                    "belongs_to": (f"db {o[0]}: {o[1]}" if o
                                   else "UNKNOWN — id resolves to no field or table"),
                    "ok": ok,
                })
    out({"dashboard": d["name"], "checked": len(report),
         "cross_database_or_unknown": bad,
         "verdict": "OK" if not bad else "BROKEN WIRING — see rows with ok:false",
         "mappings": report if (a.all or bad) else "all id-based mappings OK"})
    if bad:
        sys.exit(1)


def cmd_restore(a):
    if getattr(a, "dashboard", False):
        saved = json.loads(Path(a.file).read_text())
        if saved.get("id") != a.id and not a.force:
            die(f"restore point is for dashboard {saved.get('id')}, not {a.id}. "
                f"Pass --force to overwrite {a.id} with it deliberately.")
        body = {k: saved[k] for k in DASH_MUTABLE if k in saved}
        if saved.get("archived") is False:
            api("PUT", f"/dashboard/{a.id}", body={"archived": False})
        res = api("PUT", f"/dashboard/{a.id}", body=body)
        out({"restored": res["id"], "name": res["name"], "from": a.file,
             "fields": sorted(body)})
        return
    saved = json.loads(Path(a.file).read_text())
    if saved.get("id") != a.id and not a.force:
        die(f"restore point is for card {saved.get('id')}, not {a.id}. "
            f"Pass --force to overwrite {a.id} with it deliberately.")
    body = {k: saved[k] for k in MUTABLE if k in saved}
    was_archived = saved.get("archived")
    # Un-archive first: Metabase parks an archived card in the Trash
    # collection, so collection_id cannot be restored while it is archived.
    if was_archived is False:
        api("PUT", f"/card/{a.id}", body={"archived": False})
    res = api("PUT", f"/card/{a.id}", body=body)
    out({"restored": res["id"], "name": res["name"], "from": a.file,
         "fields": sorted(body)})


def cmd_bootstrap(a):
    url, _ = config()
    dbs = api("GET", "/database")
    dbs = dbs.get("data", dbs) if isinstance(dbs, dict) else dbs
    me = api("GET", "/user/current")

    kept = ""
    if CTX_FILE.exists():
        existing = CTX_FILE.read_text()
        if GEN_MARKER in existing:
            kept = existing.split(GEN_MARKER, 1)[1]
        elif not a.force:
            die(f"{CTX_FILE} exists and has no generated-section marker — "
                f"refusing to overwrite hand-written content. Re-run with "
                f"--force (a copy is kept next to the restore points).")
        else:
            _ensure_gitignore()
            BACKUP_DIR.mkdir(parents=True, exist_ok=True)
            bak = BACKUP_DIR / f"{time.strftime('%Y%m%dT%H%M%S')}__context.md"
            bak.write_text(existing)
            print(f"previous context saved to {bak}")

    _ensure_gitignore()
    lines = [
        "---", f"url: {url}",
        f"api_key_user: {me.get('first_name')}",
        f"superuser: {me.get('is_superuser')}",
        "---", "", "# Metabase context", "",
        "Databases visible to this API key:", "",
        "| id | name | engine |", "| -- | ---- | ------ |",
    ]
    for d in sorted(dbs, key=lambda x: x["id"]):
        lines.append(f"| {d['id']} | {d['name']} | {d.get('engine')} |")
    lines += ["", "Treat any database whose name marks it production as "
                  "read-only forever.", "", GEN_MARKER, ""]
    CTX_FILE.write_text("\n".join(lines) + (kept or "\n"))
    print(f"wrote {CTX_FILE}")


def main():
    p = argparse.ArgumentParser(prog="mb", description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("sql", help="run read-only ad-hoc SQL")
    s.add_argument("sql")
    s.add_argument("--db", type=int, required=True)
    s.add_argument("--limit", type=int, default=200,
                   help="max rows to print (0 = all)")
    s.set_defaults(fn=cmd_sql)

    s = sub.add_parser("card", help="get a card definition (JSON)")
    s.add_argument("id", type=int)
    s.set_defaults(fn=cmd_card)

    s = sub.add_parser("sql-of", help="print a card's SQL (compiles MBQL)")
    s.add_argument("id", type=int)
    s.add_argument("--compiled", action="store_true",
                   help="compile even native cards (substitutes template tags)")
    s.set_defaults(fn=cmd_sql_of)

    s = sub.add_parser("run", help="execute a card, return rows")
    s.add_argument("id", type=int)
    s.add_argument("--count", action="store_true",
                   help="row count only (server-side where possible)")
    s.add_argument("--limit", type=int, default=50,
                   help="max rows to print (0 = all)")
    s.set_defaults(fn=cmd_run)

    s = sub.add_parser("deps", help="blast radius for a card")
    s.add_argument("id", type=int)
    s.add_argument("--deep", action="store_true",
                   help="transitive dependents + possible frozen copies")
    s.add_argument("--similarity", type=float, default=0.85,
                   help="SQL similarity threshold for frozen copies")
    s.set_defaults(fn=cmd_deps)

    s = sub.add_parser("search", help="find cards/dashboards by name")
    s.add_argument("q")
    s.add_argument("--model", default="card",
                   help="card | dashboard | dataset | collection | table")
    s.add_argument("--limit", type=int, default=25)
    s.set_defaults(fn=cmd_search)

    s = sub.add_parser("dashboard", help="dashboard summary + filter wiring")
    s.add_argument("id", type=int)
    s.add_argument("--full", action="store_true")
    s.set_defaults(fn=cmd_dashboard)

    s = sub.add_parser("wiring", help="audit a dashboard's filter wiring for "
                                      "field ids from another database")
    s.add_argument("id", type=int)
    s.add_argument("--all", action="store_true",
                   help="list every id-based mapping, not just the broken ones")
    s.set_defaults(fn=cmd_wiring)

    s = sub.add_parser("backup", help="write restore point(s)")
    s.add_argument("ids", type=int, nargs="+")
    s.add_argument("--dashboard", action="store_true",
                   help="ids are dashboards, not cards")
    s.set_defaults(fn=cmd_backup)

    s = sub.add_parser("update-card", help="PUT a card (auto restore point)")
    s.add_argument("id", type=int)
    s.add_argument("--file", required=True, help="JSON of fields to change")
    s.set_defaults(fn=cmd_update)

    s = sub.add_parser("create-card", help="POST a new card")
    s.add_argument("--file", required=True)
    s.add_argument("--allow-root", action="store_true",
                   help="permit creating into the root collection")
    s.set_defaults(fn=cmd_create)

    s = sub.add_parser("create-dashboard", help="POST a new dashboard")
    s.add_argument("--file", required=True)
    s.add_argument("--allow-root", action="store_true",
                   help="permit creating into the root collection")
    s.set_defaults(fn=cmd_create_dashboard)

    s = sub.add_parser("update-dashboard",
                       help="PUT a dashboard (auto restore point)")
    s.add_argument("id", type=int)
    s.add_argument("--file", required=True, help="JSON of fields to change")
    s.add_argument("--allow-removal", action="store_true",
                   help="permit a dashcards list shorter than the current one")
    s.set_defaults(fn=cmd_update_dashboard)

    s = sub.add_parser("restore",
                       help="PUT a card (or --dashboard) back from a restore point")
    s.add_argument("id", type=int)
    s.add_argument("--file", required=True)
    s.add_argument("--dashboard", action="store_true",
                   help="restore a dashboard snapshot, not a card")
    s.add_argument("--force", action="store_true",
                   help="allow restoring from another object's snapshot")
    s.set_defaults(fn=cmd_restore)

    s = sub.add_parser("bootstrap", help="write .metabase/context.md")
    s.add_argument("--force", action="store_true",
                   help="overwrite an un-markered context.md (keeps a copy)")
    s.set_defaults(fn=cmd_bootstrap)

    a = p.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
